name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

          # Optional: golangci-lint command line arguments.
          args: --issues-exit-code=0 --disable-all -E golint,gofmt,bodyclose,gosimple,prealloc --exclude-use-default=false
